### ISSUE TITLE
Developed Script for Schedule FA Computation.

### ISSUE THREAD

**Issue by amanhigh** [sahilgupta/sbi-fx-ratekeeper#8]
First Thanks a Lot for wonderful Work done in this Repo which has helped me get Historical Rates.

Using thees i have developed a Script for Computation of Two Difficult Fields of Peak Value and Closing Value in FY.

Requesting you to review this Script and Try it out. If its Useful we can include it in Readme with Link to My Repo so others can benifit from it.

https://github.com/amanhigh/go-fun/blob/master/components/learn/tools/simple/schedule_fa.py

I have used VANTAGE API's whose Data is Correct for US Stocks and has generous Free Tier to Download Ticker Data.

File contains Readme at top of it including description, usage instructions and Sample Run Output.

Please share your feedback if any can improve script based on that. Thanks

**Comment by sahilgupta** [comment]
Appreciate the kind words, Aman. Glad you found it to be useful.

One of the main factors to take into account when calculating peak balances is the changing number of shares over the year.  In my cursory glance of your code, I didn't notice this being taken into account. I didn't get a chance to play with the code though.

Since we are not affiliated and I am unable to vouch for correctness, I am not comfortable referencing to your code.

Nevertheless, good luck for the project. It has potential to be quite useful!

**Comment by amanhigh** [comment]
Yes that is planned and your observation is correct. I am planning to build updated version which can work on last year snapshot of Holdings and Transaction history of current year.

This version still requires some logic after you get dollar values.
